### ISSUE TITLE
XCode 8.2.1 打开文件显示红色

### ISSUE THREAD

**Issue by JiesonWu** [Tencent/WeDemo#1]
![image](https://cloud.githubusercontent.com/assets/2510575/21844607/45bb4218-d82a-11e6-9e6f-db60db75a7d1.png)

**Comment by cs-jeason** [comment]
@JiesonWu 重启XCode能恢复么？

**Comment by Shunzi007** [comment]
遇到相同的问题

**Comment by UESTC-LXY** [comment]
遇到相同的问题

**Comment by cs-jeason** [comment]
因为之前重命名工程，导致文件树有问题，fix好了 @JiesonWu @Shunzi007 @UESTC-LXY #2
