### ISSUE TITLE
微信分享的问题

### ISSUE THREAD

**Issue by wangxude** [Tencent/WeDemo#11]
我是金山云iOS开发者，我使用微信分享的时候，分享本地视频的时候，为什么本地视频只可以分享到会话列表。当分享到朋友圈的时候，显示微信不支持。 （我上传的视频为10M以内，10秒以内的小视频）。如果您有时间，请回复我一下。谢谢

**Comment by cs-jeason** [comment]
暂时不支持分享本地视频到朋友圈，可以把视频上传到服务器，然后分享链接 @wangxude

**Comment by yangliguo7** [comment]
@wangxude 老哥知道 为什么微信开放标签 在安卓下不展示嘛？ 

[https://developers.weixin.qq.com/community/develop/doc/0002ea1854cb28ecdd0e5f0455b400?highLine=vue3](url)
